/*
 *  Copyright 2016 CNRS & Universite Lille 1. All rights reserved.
 *  
 *  Licensed under the GRASP Open Source License V1.0 (see LICENSE file)
 */

/* 
 * File:   grasp_error_codes.h
 * Author: david
 *
 * Created on 29 de July de 2017, 8:20
 */

#ifndef GRASP_ERROR_CODES_H
#define GRASP_ERROR_CODES_H

#define GRASP_ERROR_CONTROLLER_READ_SETTINGS_NOT_ENOUGH_ARGUMENTS -100001

#define GRASP_ERROR_SETTING_READ_HELP -200001
#define GRASP_ERROR_SETTINGS_PRINT_VERSION -200002
#define GRASP_ERROR_SETTINGS_READ -200003
#define GRASP_ERROR_SETTINGS_PRINT_DEBUG -200004

#define GRASP_ERROR_INPUT_NO_INPUT_FILES -300001
#define GRASP_ERROR_INPUT_INIT_INVERSION -302000

#define GRASP_ERROR_CONTROLLER_SEGMENT_NOT_INVERTED -400001
#define GRASP_ERROR_CONTROLLER_RETRIEVAL_WANTS_TO_FINISH -400002
#define GRASP_ERROR_CONTROLLER_EMPTY_TILE -400003

#define GRASP_ERROR_DRIVER -500000
#define GRASP_ERROR_TRANSFORMER -600000
#define GRASP_ERROR_OUTPUT_SEGMENT_FUNCTION -700000
#define GRASP_ERROR_OUTPUT_CURRENT_FUNCTION -800000
#define GRASP_ERROR_OUTPUT_TILE_FUNCTION -900000
#define GRASP_ERROR_OUTPUT_ITERATION_FUNCTION -1000000


#endif /* GRASP_ERROR_CODES_H */

